sonar.projectKey=veterinaria-backend
sonar.projectName=Veterinaria Backend
sonar.sources=src
sonar.exclusions=node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
sonar.login=sqa_4547c0c69640127ca90a8d87710a0571378fed29